name 'developer-base'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures developer-base'
long_description 'Installs/Configures developer-base'
version '0.1.0'
